// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");

var linearAnimation = Curry._1(Css.keyframes, {
      hd: [
        0,
        {
          hd: Css.backgroundPosition({
                NAME: "hv",
                VAL: [
                  "zero",
                  "zero"
                ]
              }),
          tl: /* [] */0
        }
      ],
      tl: {
        hd: [
          100,
          {
            hd: Css.backgroundPosition({
                  NAME: "hv",
                  VAL: [
                    Css.px(200),
                    "zero"
                  ]
                }),
            tl: /* [] */0
          }
        ],
        tl: /* [] */0
      }
    });

var buttonAnimation = Curry._1(Css.style, {
      hd: Css.before({
            hd: Css.contentRule({
                  NAME: "text",
                  VAL: ""
                }),
            tl: {
              hd: Css.display("block"),
              tl: {
                hd: Css.height(Css.pct(100)),
                tl: {
                  hd: Css.width(Css.pct(100)),
                  tl: {
                    hd: Css.borderRadius(Css.px(3)),
                    tl: {
                      hd: Css.transform(Css.scale(1.02, 1.08)),
                      tl: {
                        hd: Css.position(Css.absolute),
                        tl: {
                          hd: Css.background(Css.linearGradient(Css.deg(90), {
                                    hd: [
                                      Css.zero,
                                      Css.rgb(0, 0, 255)
                                    ],
                                    tl: {
                                      hd: [
                                        Css.px(100),
                                        Css.rgb(255, 0, 0)
                                      ],
                                      tl: /* [] */0
                                    }
                                  })),
                          tl: {
                            hd: Css.backgroundPosition({
                                  NAME: "hv",
                                  VAL: [
                                    Css.px(55),
                                    Css.px(0)
                                  ]
                                }),
                            tl: {
                              hd: Css.top(Css.zero),
                              tl: {
                                hd: Css.animationDuration(1),
                                tl: {
                                  hd: Css.animationIterationCount(Css.infinite),
                                  tl: {
                                    hd: Css.animationName(linearAnimation),
                                    tl: {
                                      hd: Css.left(Css.zero),
                                      tl: {
                                        hd: Css.zIndex(-1),
                                        tl: {
                                          hd: Css.backgroundColor(Css.hex("f00")),
                                          tl: {
                                            hd: Css.boxSizing(Css.borderBox),
                                            tl: /* [] */0
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }),
      tl: /* [] */0
    });

exports.linearAnimation = linearAnimation;
exports.buttonAnimation = buttonAnimation;
/* linearAnimation Not a pure module */
