// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");

var flickerKeyframes = Curry._1(Css.keyframes, {
      hd: [
        0,
        {
          hd: Css.opacity(0),
          tl: /* [] */0
        }
      ],
      tl: {
        hd: [
          10,
          {
            hd: Css.opacity(0.1),
            tl: /* [] */0
          }
        ],
        tl: {
          hd: [
            20,
            {
              hd: Css.opacity(0),
              tl: /* [] */0
            }
          ],
          tl: {
            hd: [
              30,
              {
                hd: Css.opacity(0),
                tl: /* [] */0
              }
            ],
            tl: {
              hd: [
                40,
                {
                  hd: Css.opacity(0),
                  tl: /* [] */0
                }
              ],
              tl: {
                hd: [
                  50,
                  {
                    hd: Css.opacity(0.5),
                    tl: {
                      hd: Css.left(Css.px(6)),
                      tl: /* [] */0
                    }
                  }
                ],
                tl: {
                  hd: [
                    60,
                    {
                      hd: Css.opacity(0),
                      tl: /* [] */0
                    }
                  ],
                  tl: {
                    hd: [
                      70,
                      {
                        hd: Css.opacity(0),
                        tl: /* [] */0
                      }
                    ],
                    tl: {
                      hd: [
                        80,
                        {
                          hd: Css.opacity(0.3),
                          tl: /* [] */0
                        }
                      ],
                      tl: {
                        hd: [
                          90,
                          {
                            hd: Css.opacity(0),
                            tl: /* [] */0
                          }
                        ],
                        tl: {
                          hd: [
                            100,
                            {
                              hd: Css.opacity(0.6),
                              tl: {
                                hd: Css.left(Css.px(-2)),
                                tl: /* [] */0
                              }
                            }
                          ],
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    });

var flickerAnimation = Curry._1(Css.style, {
      hd: Css.animationName(flickerKeyframes),
      tl: {
        hd: Css.animationDuration(1),
        tl: {
          hd: Css.animationIterationCount(Css.infinite),
          tl: {
            hd: Css.animationTimingFunction(Css.linear),
            tl: /* [] */0
          }
        }
      }
    });

var flickerKeyframes1 = Curry._1(Css.keyframes, {
      hd: [
        0,
        {
          hd: Css.opacity(0),
          tl: /* [] */0
        }
      ],
      tl: {
        hd: [
          10,
          {
            hd: Css.opacity(0.1),
            tl: /* [] */0
          }
        ],
        tl: {
          hd: [
            20,
            {
              hd: Css.opacity(0),
              tl: /* [] */0
            }
          ],
          tl: {
            hd: [
              30,
              {
                hd: Css.opacity(0),
                tl: /* [] */0
              }
            ],
            tl: {
              hd: [
                40,
                {
                  hd: Css.opacity(0),
                  tl: /* [] */0
                }
              ],
              tl: {
                hd: [
                  50,
                  {
                    hd: Css.opacity(0.5),
                    tl: {
                      hd: Css.right(Css.px(6)),
                      tl: /* [] */0
                    }
                  }
                ],
                tl: {
                  hd: [
                    60,
                    {
                      hd: Css.opacity(0),
                      tl: /* [] */0
                    }
                  ],
                  tl: {
                    hd: [
                      70,
                      {
                        hd: Css.opacity(0),
                        tl: /* [] */0
                      }
                    ],
                    tl: {
                      hd: [
                        80,
                        {
                          hd: Css.opacity(0.3),
                          tl: /* [] */0
                        }
                      ],
                      tl: {
                        hd: [
                          90,
                          {
                            hd: Css.opacity(0),
                            tl: /* [] */0
                          }
                        ],
                        tl: {
                          hd: [
                            100,
                            {
                              hd: Css.opacity(0.6),
                              tl: {
                                hd: Css.right(Css.px(-2)),
                                tl: /* [] */0
                              }
                            }
                          ],
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    });

var flickerAnimation1 = Curry._1(Css.style, {
      hd: Css.animationName(flickerKeyframes1),
      tl: {
        hd: Css.animationDuration(1000),
        tl: {
          hd: Css.animationIterationCount(Css.infinite),
          tl: {
            hd: Css.animationTimingFunction(Css.linear),
            tl: /* [] */0
          }
        }
      }
    });

exports.flickerKeyframes = flickerKeyframes;
exports.flickerAnimation = flickerAnimation;
exports.flickerKeyframes1 = flickerKeyframes1;
exports.flickerAnimation1 = flickerAnimation1;
/* flickerKeyframes Not a pure module */
