// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Dialog(Props) {
  var dialog = Props.dialog;
  var buttonText = Props.buttonText;
  var onButtonPressed = Props.onButtonPressed;
  return React.createElement("div", {
              className: "p-6 w-56 h-auto bg-gray-600  space-y-6 relative box-border"
            }, React.createElement("div", undefined, dialog), React.createElement("button", {
                  className: "mx-auto my-0 block",
                  onClick: onButtonPressed
                }, buttonText));
}

var make = Dialog;

var $$default = Dialog;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
