// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var HomeStyles$MyBlog = require("../styles/HomeStyles.bs.js");
var SiteLogo = require("src/components/SiteLogo").default;
var Shakthihead = require("src/components/shakthihead").default;

function Home(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: Curry._1(Css.merge, {
                        hd: "p-6 w-56 h-8 absolute left-0 text-gray-200 text-5xl",
                        tl: {
                          hd: HomeStyles$MyBlog.flickerAnimation,
                          tl: /* [] */0
                        }
                      }),
                  style: {
                    fontFamily: "Courier New"
                  }
                }, "What have I become?"), React.createElement("div", {
                  className: "flex flex-col mx-auto w-px-500 "
                }, React.createElement(SiteLogo, {
                      className: "w-64 m-auto"
                    }), React.createElement("div", {
                      className: "w-full m-auto relative "
                    }, React.createElement("img", {
                          className: "w-full",
                          src: "/vman.png"
                        }), React.createElement(Shakthihead, {
                          className: Curry._1(Css.merge, {
                                hd: "absolute top-0",
                                tl: {
                                  hd: Curry._1(Css.style, {
                                        hd: Css.right(Css.pct(50)),
                                        tl: {
                                          hd: Css.transform(Css.translateX(Css.pct(50))),
                                          tl: {
                                            hd: Css.width(Css.pct(23)),
                                            tl: {
                                              hd: Css.height(Css.pct(23)),
                                              tl: /* [] */0
                                            }
                                          }
                                        }
                                      }),
                                  tl: /* [] */0
                                }
                              })
                        }))), React.createElement("div", {
                  className: Curry._1(Css.merge, {
                        hd: "p-6 w-56 h-8 absolute right-0 text-gray-200 text-2xl",
                        tl: {
                          hd: HomeStyles$MyBlog.flickerAnimation1,
                          tl: /* [] */0
                        }
                      }),
                  style: {
                    fontFamily: "Courier New"
                  }
                }, "We're all puppets, Laurie. I'm just a puppet who can see the strings."));
}

var make = Home;

var $$default = Home;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Css Not a pure module */
