// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Page(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "h-screen w-screen bg-black overflow-y-hidden overflow-x-hidden"
            }, children);
}

var make = Page;

var $$default = Page;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
